[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs -d"

[alias]
rp2040-build = "build --no-default-features --features rp2040 --target thumbv6m-none-eabi"
rp2350-build = "build --no-default-features --features rp2350 --target thumbv8m.main-none-eabihf"

[target.thumbv6m-none-eabi]
linker = "flip-link"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "no-vectorize-loops",
]

[target.thumbv8m.main-none-eabihf]
linker = "flip-link"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "no-vectorize-loops",
]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"
